export enum RequestMethodEnum {
  PAM_CATEGORIES = 'pam.categories',
  PAM_CATEGORY_VENDORS = 'pam.category_vendors',
  PAM_GET_SERVICE_BALANCE = 'pam.get_service_balance',
  PAM_GET_VENDOR_BY_ID = 'pam.get_vendor_by_id',
  PAM_VENDOR_FORM = 'pam.vendor_form_v2',
  PAM_CHECK = 'pam.check',
  PAM_PAY_BY_CASH = 'pam.pay_by_cash',
  PAM_PREPARE_PAY = 'pam.prepare_pay',
  PAM_SEND_SMS = 'pam.send_sms',
  PAM_CONFIRM_PAY = 'pam.confirm_pay',
  PAM_PAY_RESEND_SMS = 'pam.pay_resend_sms',
  PAM_CHECK_PAYMENT = 'pam.check_payment',
  PAM_P2P_INFO = 'pam.p2p_info',
  PAYSYS_GET_FISCAL_CHEQUE = 'paysys.get_fiscal_cheque',
  PAM_GET_FISCAL_DETAILS = 'pam.get_fiscal_details',
  PAYSYS_GET_AGENT_DEPOSITS = 'paysys.get_agent_deposits',
  PAM_GET_SERVICE_BALANCE_HISTORY = 'pam.get_service_balance_history',
  PAM_GET_PAYMENT_TRANSACTIONS_CSV = 'pam.get_payment_transactions_csv',
  PAM_GET_CHEQUE_DETAILS = 'pam.get_cheque_details',
  CASH2CARD_PREPARE_REMITTANCE = 'cash2card.prepare_remittance',
  CASH2CARD_CONFIRM_REMITTANCE = 'cash2card.confirm_remittance',
}
